const themes =
    [
        "Default",
        "A 11 Y Dark",
        "A 11 Y Light",
        "Agate",
        "An Old Hope",
        "Androidstudio",
        "Arduino Light",
        "Arta",
        "Ascetic",
        "Atelier Cave Dark",
        "Atelier Cave Light",
        "Atelier Dune Dark",
        "Atelier Dune Light",
        "Atelier Estuary Dark",
        "Atelier Estuary Light",
        "Atelier Forest Dark",
        "Atelier Forest Light",
        "Atelier Heath Dark",
        "Atelier Heath Light",
        "Atelier Lakeside Dark",
        "Atelier Lakeside Light",
        "Atelier Plateau Dark",
        "Atelier Plateau Light",
        "Atelier Savanna Dark",
        "Atelier Savanna Light",
        "Atelier Seaside Dark",
        "Atelier Seaside Light",
        "Atelier Sulphurpool Dark",
        "Atelier Sulphurpool Light",
        "Atom One Dark Reasonable",
        "Atom One Dark",
        "Atom One Light",
        "Brown Paper",
        "Codepen Embed",
        "Color Brewer",
        "Darcula",
        "Dark",
        "Docco",
        "Dracula",
        "Far",
        "Foundation",
        "Github Gist",
        "Github",
        "Gml",
        "Googlecode",
        "Gradient Dark",
        "Gradient Light",
        "Grayscale",
        "Gruvbox Dark",
        "Gruvbox Light",
        "Hopscotch",
        "Hybrid",
        "Idea",
        "Ir Black",
        "Isbl Editor Dark",
        "Isbl Editor Light",
        "Kimbie Dark",
        "Kimbie Light",
        "Lightfair",
        "Lioshi",
        "Magula",
        "Mono Blue",
        "Monokai Sublime",
        "Monokai",
        "Night Owl",
        "Nnfx Dark",
        "Nnfx",
        "Nord",
        "Obsidian",
        "Ocean",
        "Paraiso Dark",
        "Paraiso Light",
        "Pojoaque",
        "Purebasic",
        "Qtcreator Dark",
        "Qtcreator Light",
        "Railscasts",
        "Rainbow",
        "Routeros",
        "School Book",
        "Shades Of Purple",
        "Solarized Dark",
        "Solarized Light",
        "Srcery",
        "Stackoverflow Dark",
        "Stackoverflow Light",
        "Sunburst",
        "Tomorrow Night Blue",
        "Tomorrow Night Bright",
        "Tomorrow Night Eighties",
        "Tomorrow Night",
        "Tomorrow",
        "Vs",
        "Vs 2015",
        "Xcode",
        "Xt 256",
        "Zenburn"
    ]
const themeValue = [
    'default.css',
    'a11y-dark.css',
    'a11y-light.css',
    'agate.css',
    'an-old-hope.css',
    'androidstudio.css',
    'arduino-light.css',
    'arta.css',
    'ascetic.css',
    'atelier-cave-dark.css',
    'atelier-cave-light.css',
    'atelier-dune-dark.css',
    'atelier-dune-light.css',
    'atelier-estuary-dark.css',
    'atelier-estuary-light.css',
    'atelier-forest-dark.css',
    'atelier-forest-light.css',
    'atelier-heath-dark.css',
    'atelier-heath-light.css',
    'atelier-lakeside-dark.css',
    'atelier-lakeside-light.css',
    'atelier-plateau-dark.css',
    'atelier-plateau-light.css',
    'atelier-savanna-dark.css',
    'atelier-savanna-light.css',
    'atelier-seaside-dark.css',
    'atelier-seaside-light.css',
    'atelier-sulphurpool-dark.css',
    'atelier-sulphurpool-light.css',
    'atom-one-dark-reasonable.css',
    'atom-one-dark.css',
    'atom-one-light.css',
    'brown-paper.css',
    'codepen-embed.css',
    'color-brewer.css',
    'darcula.css',
    'dark.css',
    'docco.css',
    'dracula.css',
    'far.css',
    'foundation.css',
    'github-gist.css',
    'github.css',
    'gml.css',
    'googlecode.css',
    'gradient-dark.css',
    'gradient-light.css',
    'grayscale.css',
    'gruvbox-dark.css',
    'gruvbox-light.css',
    'hopscotch.css',
    'hybrid.css',
    'idea.css',
    'ir-black.css',
    'isbl-editor-dark.css',
    'isbl-editor-light.css',
    'kimbie.dark.css',
    'kimbie.light.css',
    'lightfair.css',
    'lioshi.css',
    'magula.css',
    'mono-blue.css',
    'monokai-sublime.css',
    'monokai.css',
    'night-owl.css',
    'nnfx-dark.css',
    'nnfx.css',
    'nord.css',
    'obsidian.css',
    'ocean.css',
    'paraiso-dark.css',
    'paraiso-light.css',
    'pojoaque.css',
    'purebasic.css',
    'qtcreator_dark.css',
    'qtcreator_light.css',
    'railscasts.css',
    'rainbow.css',
    'routeros.css',
    'school-book.css',
    'shades-of-purple.css',
    'solarized-dark.css',
    'solarized-light.css',
    'srcery.css',
    'stackoverflow-dark.css',
    'stackoverflow-light.css',
    'sunburst.css',
    'tomorrow-night-blue.css',
    'tomorrow-night-bright.css',
    'tomorrow-night-eighties.css',
    'tomorrow-night.css',
    'tomorrow.css',
    'vs.css',
    'vs2015.css',
    'xcode.css',
    'xt256.css',
    'zenburn.css'
]
module.exports = { themeValue, themes }